### PR TITLE
Added support for AVR-DA and DB devices

### PR DESCRIPTION
**Pull request by jhol**

### CODE REVIEW

**Comment by jhol** [comment]
This patch adds support for these devices to GCC:
https://gcc.gnu.org/pipermail/gcc-patches/2022-April/592669.html

**Comment by dl8dtl** [comment]
Funny, I started doing that merge myself a couple of weeks ago. ;-)
Curious, did you actually try whether the EEPROM routines do work? That's where I holded back my initial attempt, after reading a bit of and on, seeing the NVIC controller in these newer devices is quite a bit different from the previous Xmega one.

So it would be good to know if it's confirmed to work or not.

**Comment by jhol** [comment]
> Curious, did you actually try whether the EEPROM routines do work? That's where I holded back my initial attempt, after reading a bit of and on, seeing the NVIC controller in these newer devices is quite a bit different from the previous Xmega one.

Ahh... sorry, that was on my todo list, but I negelected to cover that part. I don't have any need for EEPROM-write in my application, so I didn't cover it so far.

Everything else seems to be working great. My project uses registers from CLK, INT, SLP, CCL, UART, TWI, SPI, PORT, PORTMUX, FUSE, and so far I have encountered zero issues.

**Comment by sprintersb** [comment]
> This patch adds support for these devices to GCC:
> https://gcc.gnu.org/pipermail/gcc-patches/2022-April/592669.html

Hi Joel, tere are some bugs in that GCC patch, so I allow me to write here.

Only devices of families `avrtiny` and `avrxmega3` support flash-in-ram-address-space. Hence the last entry in
```
AVR_MCU ("avr64db64", ARCH_AVRXMEGA2, ..., 0x8000, 0x10000)
```
must be `0`. Non-zero values are ignored for that family, so the entry of `0x10000` is confusing at least.

The 2nd-last value must be the flash size in bytes, presumably something around 0x10000 for a AVR64DBxx.

Dito for similar entries under avrxmega2 and avrxmega4,

**Comment by jhol** [comment]
@sprintersb Thanks for the review. I'll revise the patch and resubmit it..

**Pull request merged**
