### PR TITLE
include/avr/io*.h: Update I/O header files

### PR DESCRIPTION
**Pull request by maribu**
This copies avr/include/avr/io*.h from Microchips "AVR 8-Bit Toolchain (Linux)" in version 3.7.0 into the repo.

### CODE REVIEW

**Comment by maribu** [comment]
Likely it is easier to just fetch the latest vendor header files and push the changes directly to the repo than validating this PR. But anyway, this PR can at least serve as a reminder that there is benefit in updating the header files again :-)

**Comment by sprintersb** [comment]
Many removes in avr/io. h for what reason? Presumably Mchip just privides device packs, whereas AVR-LibC has native support.

Also many changes in comments and white spaces adding quite some noise.

**Comment by maribu** [comment]
I just copied the files from microchip as-is. I don't see a benefit in fixing the whitespace issues in the microchip sources; those files are maintained by Microchip and duplicating maintenance effort downstream is not helpful.

To be honest, I wonder why the files are part of the repo in the first place. IMO they should be removed from the repo.

The makefile could add some `make vendorheaders` target for convenience that would download a release, compare the zip's checksum, and install the `io*.h`. That way updating the vendor header files would involve changing two lines only, the download URL and the checksum.

**Comment by sprintersb** [comment]
In the past there were cases of bogus hardware descriptions / mchip headers. So a possibility to maintain on AVR-LibC level is desirable.

**Comment by sprintersb** [comment]
IMO its almost impossible to review such big, monolithic changes.  Just copying over files might not do the trick, for example you are removing support for ATmega808 and for many other devices.

**Comment by maribu** [comment]
Sorry for the late reply.

The issue with the missing defines and types in the vendor headers files for the ATxmega MCUs I am working with has been resolved in `main` in the meantime.

**Pull request closed without merging**
